### ISSUE TITLE
DoesNotExist at /admin/login/

### ISSUE THREAD

**Issue by jhogan7utk** [ecds/OpenTourBuilder-Client#1]
We are installing OpenTourBuilder at AUC Woodruff Library.  Initially, I was able to login with the admin account and could create sites, tours, etc.  When I tried to create a tour stop AND upload media at the same time, I received this error message: OSError at /admin/tour/tourstop/add/   /   [Errno 13] Permission denied:  '/home/ocitadmin/OpenTourBuilder-Server/tours/media/'.

I was instructed to run this command:  chown -R user:group /home/ocitadmin/OpenTourBuilder-Server.  I did so using ocitadmin:ocitadmin in place of user:group.  Now I am getting this message:
![image](https://cloud.githubusercontent.com/assets/26774102/24467743/b551e3f8-1483-11e7-9351-b7714f4dd4c7.png)

Any ideas what I need to do?  To give a little further context, when the software was installed the domain and api were named digitaltours.auctr.edu and api.digitaltours.auctr.edu.  We subsequently changed that to auccommunitytour.auctr.edu (and the corresponding api address).

**Comment by jayvarner** [comment]
In the Django admin, got to "Sites":

<img width="465" alt="site_administration___mobile_tours_admin" src="https://cloud.githubusercontent.com/assets/24685/24469977/54fcddde-148b-11e7-9bcb-43539913de5c.png">

If there is an existing record, edit that one. If there isn't one, create a new one. Set both domain and display names to `http://api.auccommunitytour.auctr.edu`

**Comment by jhogan7utk** [comment]
I can't get back into the django admin site.  Whenever I try by going to api.auccommunitytour.auctr.edu/admin.  I get that "DoesNotExist" error.  I was able to login earlier today, however.  Currently the existing record is set to auccommunitytour.auctr.edu (wihout the api prefix). The display name is not the same, however.

**Comment by jayvarner** [comment]
Assuming you have shell access you can do the following:

```shell
cd /home/ocitadmin/OpenTourBuilder-Server
venv bin activate
python manage.py shell
```

This will put you in a Python shell. To edit the site do:


```python
from django.contrib.sites.models import Site
site = Site.objects.all()[0]
site.name = 'http://api.auccommunitytour.auctr.edu'
site.domain = 'http://api.auccommunitytour.auctr.edu'
site.save()
```
**UPDATE** I added the command to open up the Django shell.

**Comment by clifflandis** [comment]
I followed the instructions, but no luck.... We're still getting the DoesNotExist error on the http://api.auccommunitytour.auctr.edu/admin/ site. 

![capture](https://cloud.githubusercontent.com/assets/1706163/24523544/5c9acf48-1561-11e7-9478-0e0cff36de34.PNG)

**Comment by jayvarner** [comment]
I get redirected to a generic 404 when I try visit http://api.auccommunitytour.auctr.edu/admin/.

Is the DNS for auccommunitytour.auctr.edu and api.auccommunitytour.auctr.edu set up to point to your server? Or is there a firewall preventing me from seeing it?

My Friday is miserably booked. I could come down to Clark Monday morning. If this has reached a critical point, I could make some time Friday between noon and 2 for a call or a live chat.

**Comment by jhogan7utk** [comment]
Hi Jay,

Initially I was able to login to the api.auccommunitytour.auctr.edu/admin link.  I couldn’t add media to tour stops, however.  Once I ran the “chown” command that was suggested to fix that issue, I was indeed able to add media to a tour stop. Unfortunately, when I tried to logout after that, I started getting the “does not exist” error. After that, I couldn’t get to the login page again.

I don’t know if that makes sense or not.

I’m not here on Monday, but I could probably fit in some time around 1pm today for a call.  I’ll see if Cliff can do that as well.  I think Cliff will be here on Monday, but I don’t know for sure.

Thanks!!

Josh Hogan
Metadata & Digital Resources Librarian
Atlanta University Center Robert W. Woodruff Library
111 James P. Brawley Drive, SW
Atlanta, GA  30314
404-978-2081 (v)
http://www.auctr.edu<http://www.auctr.edu/>
jhogan@auctr.edu<mailto:jhogan@auctr.edu>

[cid:image001.jpg@01D2A9FE.29158830]

We will always provide service that exceeds the customer’s expectation… Because we care!

**Comment by clifflandis** [comment]
I'm available for a call today at 1pm and all day Monday.

**Comment by jhogan7utk** [comment]
Hi Jay,

Can you make it to AUC Woodruff on Tuesday or Thursday?  That way both Cliff and I can be present.

Thanks!!

Josh Hogan
Metadata & Digital Resources Librarian
Atlanta University Center Robert W. Woodruff Library
111 James P. Brawley Drive, SW
Atlanta, GA  30314
404-978-2081 (v)
http://www.auctr.edu<http://www.auctr.edu/>
jhogan@auctr.edu<mailto:jhogan@auctr.edu>

[cid:image001.jpg@01D2AA38.B2927980]

We will always provide service that exceeds the customer’s expectation… Because we care!

**Comment by jayvarner** [comment]
Thursday is very doable. I have a meeting at GSU that morning.

**Comment by jhogan7utk** [comment]
Hi Jay,

I am open on Thursday afternoon, if that works for you.

Josh
________________________________________

**Comment by jayvarner** [comment]
Perfect, tell me when and where and I'll be there.

**Comment by jhogan7utk** [comment]
Hi Jay,

How about Thursday at 2pm?  We can meet at the back entrance of AUC Woodruff Library.  I can send you directions if you need.

Thanks!


Josh Hogan
Metadata & Digital Resources Librarian
Atlanta University Center Robert W. Woodruff Library
111 James P. Brawley Drive, SW
Atlanta, GA  30314
404-978-2081 (v)
http://www.auctr.edu<http://www.auctr.edu/>
jhogan@auctr.edu<mailto:jhogan@auctr.edu>

[cid:image001.jpg@01D2AD23.47164C70]

We will always provide service that exceeds the customer’s expectation… Because we care!

**Comment by jayvarner** [comment]
I deleted some posts that had email address shown. Anyway, I'm looking forward to Thursday afternoon. I'm 98% sure I know where to go.

**Comment by jayvarner** [comment]
We fixed this back in April. Problem with a breaking change in Django RESTFramework. Solution was to peg it to an earlier version since OpenTourBuilder 3.0 is in active development 🚀

**Comment by SASIN83** [comment]
Another thing you can do is simple if you get some error or just want to change site. 
1. Download '[sqlitebrowser ](https://sqlitebrowser.org)'
2. open your sqlite.db
3. search for django_sites
4. change domain name and display name to whatever you want
